"""
Retrieval + reranking + grounded answer generation.

Fix vs. the original `rag.py`: the previous implementation built a LangChain
LCEL pipeline with `{"history": RunnablePassthrough(), "context":
RunnablePassthrough(), "question": RunnablePassthrough()}`, which — because
RunnablePassthrough() just returns whatever input it receives — fed the
*entire* input dict into each of the `{history}` / `{context}` / `{question}`
prompt slots instead of routing each field to its own slot. Here the prompt
is simply formatted directly with the right values, which is both correct
and easier to follow.

The prompt also no longer asks the model to write timestamp citations into
the answer text itself. Timestamps are unreliable when generated by an LLM
from memory; instead, the backend returns the *real* timestamps from the
retrieved chunks as structured `sources`, and the UI renders them as
clickable citations. The model's only job is to answer using the context.
"""
from typing import List, Optional

from langchain_community.vectorstores import FAISS
from langchain_core.documents import Document
from langchain_core.prompts import PromptTemplate

from app.utils.embedding import get_reranker
from app.utils.lang import LanguageInfo
from app.utils.llm import get_llm
from app.utils.logging import logger
from config import config

_ANSWER_PROMPT = PromptTemplate.from_template(
    """{style}

You are a helpful assistant answering questions about a YouTube video (or playlist) using ONLY the transcript excerpts provided below. Do not use outside knowledge and do not guess.

Rules:
- If the answer is not contained in the transcript excerpts, say so plainly (e.g. "The video doesn't cover that.") — do not make anything up.
- Do not include timestamps, citations, or source references in your answer — those are shown separately to the user.
- Be direct and concise. Use the conversation history only to understand what the user means (e.g. "it", "that"), not as a source of facts.

Conversation history:
{history}

Transcript excerpts:
{context}

Question: {question}

Answer:"""
)


def _style_for(language_info: LanguageInfo) -> str:
    language, tone = language_info["language"], language_info["tone"]
    if language == "English":
        return (
            "Respond in friendly, casual English." if tone == "casual"
            else "Respond in clear, professional English."
        )
    if language == "Hinglish":
        return "Respond naturally in Hinglish (Hindi-English mix, Roman script), casual and conversational."
    return "Respond in natural, fluent Hindi (Devanagari script)."


def retrieve_and_rerank(
    vector_store: FAISS,
    question: str,
    current_time: Optional[float] = None,
    video_id_filter: Optional[str] = None,
    k_retrieve: Optional[int] = None,
    k_final: Optional[int] = None,
) -> List[Document]:
    """Similarity search -> optional video filter -> cross-encoder rerank ->
    optional small proximity boost for 'ask about this moment'."""
    k_retrieve = k_retrieve or config.RETRIEVE_TOP_K
    k_final = k_final or config.RERANK_TOP_K

    retriever = vector_store.as_retriever(search_type="similarity", search_kwargs={"k": k_retrieve})
    docs = retriever.invoke(question)

    if video_id_filter:
        docs = [d for d in docs if d.metadata.get("video_id") == video_id_filter]

    if not docs:
        return []

    reranker = get_reranker()
    pairs = [[question, d.page_content] for d in docs]
    scores = list(reranker.predict(pairs))

    if current_time is not None:
        for i, doc in enumerate(docs):
            start = float(doc.metadata.get("start", 0.0))
            distance = abs(start - current_time)
            proximity_bonus = max(0.0, 1.0 - min(distance, 120.0) / 120.0) * 0.5
            scores[i] += proximity_bonus

    ranked = sorted(zip(docs, scores), key=lambda x: x[1], reverse=True)
    return [d for d, _ in ranked[:k_final]]


async def generate_answer(
    language_info: LanguageInfo,
    history_str: str,
    context: str,
    question: str,
) -> str:
    llm = get_llm()
    prompt = _ANSWER_PROMPT.format(
        style=_style_for(language_info),
        history=history_str,
        context=context,
        question=question,
    )
    logger.debug("Generating answer via Ollama")
    result = await llm.ainvoke(prompt)
    return result.strip()
